onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -radix unsigned /tb_encode/i
add wave -noupdate /tb_encode/k
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/clk_i
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/rst_ni
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/csr_i/csr_addr_i
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/csr_i/csr_wr_data_i
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/csr_i/csr_wr_en_i
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/csr_i/csr_req_valid_i
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/csr_i/csr_req_ready_o
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/csr_i/csr_rd_data_o
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/csr_i/csr_rsp_valid_o
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/csr_i/csr_rsp_ready_i
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/csr_i/csr_start_o
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/csr_i/in_valid
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/csr_i/in_value
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/csr_i/input_done
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/csr_i/running
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/csr_i/in_ready
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/csr_i/output_valid
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/csr_i/out
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/csr_i/sliding_window_mode
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/csr_i/signature_encoding_mode
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/csr_i/xor_binding_mode
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/csr_i/shift_binding_mode
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/csr_i/shift_amount_in
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/csr_i/acc1_mode
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/csr_i/cdt_mode
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/csr_i/acc2_mode
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/csr_i/window1_size
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/csr_i/cdt_k_factor
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/csr_i/thr1_val
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/csr_i/thr2_val
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/csr_i/or_mode
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/csr_i/am_addr_max
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/csr_i/csr_input_o
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/csr_i/csr_status_i
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/csr_i/csr_p_binding_o
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/csr_i/csr_p_bundling_o
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/csr_i/csr_am_max_o
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/csr_i/req_success
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/csr_i/rsp_success
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/start
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/running
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/in_valid
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/in_ready
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/input_done
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/out
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/output_valid
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/in_value
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/encoded_hv
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/encoding_done
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/bundling_i/clk_i
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/sliding_window_mode
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/signature_encoding_mode
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/xor_binding_mode
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/shift_binding_mode_in
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/shift_amount_in
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/or_mode
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/acc1_mode
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/cdt_mode
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/acc2_mode
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/cdt_k_factor
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/thr1_val
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/thr2_val
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/window1_size
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/am_addr
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/am_ren
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/am_rdata
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/am_addr_max
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/window1_amount
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/in_value_mapper
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/in_valid_mapper
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/im_en
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/shift_binding_mode
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/shift_amount
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/binding_done
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/hv_im_out
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/hv_binding_out
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/bundling_i/clk_i
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/bundling_i/rst_ni
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/bundling_i/hv_in
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/bundling_i/start_op
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/bundling_i/input_done
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/bundling_i/or_mode
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/bundling_i/acc1_mode
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/bundling_i/cdt_mode
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/bundling_i/acc2_mode
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/bundling_i/cdt_k_factor
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/bundling_i/thr1_val
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/bundling_i/thr2_val
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/bundling_i/acc_reset
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/bundling_i/window1_size
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/bundling_i/hv_bundling_out
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/bundling_i/out_ready
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/bundling_i/in_counter
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/bundling_i/acc1_regs
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/bundling_i/thr1_out
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/bundling_i/reg1_out
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/bundling_i/cdt_out
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/bundling_i/stage1_out
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/bundling_i/cond1
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/bundling_i/start_op_prev
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/bundling_i/cond2
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/bundling_i/cond2_prev
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/bundling_i/stage1_ready
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/bundling_i/acc2_counter
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/bundling_i/acc2_regs
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/bundling_i/thr2_effective
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/bundling_i/thr2_calc
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/bundling_i/stage1_ready_prev
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/bundling_i/thr2_out
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/acc_reset
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/out_am_valid
add wave -noupdate /tb_encode/i_top_wrapper/am_i/clk_i
add wave -noupdate /tb_encode/i_top_wrapper/am_i/addr
add wave -noupdate /tb_encode/i_top_wrapper/am_i/wen
add wave -noupdate /tb_encode/i_top_wrapper/am_i/ren
add wave -noupdate /tb_encode/i_top_wrapper/am_i/wdata
add wave -noupdate /tb_encode/ext_am_wen
add wave -noupdate /tb_encode/ext_am_ren
add wave -noupdate /tb_encode/i_top_wrapper/am_i/rdata
add wave -noupdate /tb_encode/i_top_wrapper/am_i/addr_i
add wave -noupdate /tb_encode/i_top_wrapper/am_i/web
add wave -noupdate /tb_encode/i_top_wrapper/am_i/csb
add wave -noupdate {/tb_encode/i_top_wrapper/am_i/process_for_mem[15]/skyram_inst/mem}
add wave -noupdate {/tb_encode/i_top_wrapper/am_i/process_for_mem[0]/skyram_inst/mem}
add wave -noupdate {/tb_encode/i_top_wrapper/am_i/process_for_mem[1]/skyram_inst/mem}
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/am_top_i/clk_i
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/am_top_i/rst_ni
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/am_top_i/encoded_hv
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/am_top_i/encoding_done
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/am_top_i/am_addr
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/am_top_i/am_ren
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/am_top_i/am_rdata
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/am_top_i/am_addr_max
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/am_top_i/out
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/am_top_i/output_valid
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/am_top_i/reading_am
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/am_top_i/read_am_addr
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/am_top_i/and_out
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/am_top_i/read_new_hv
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/am_top_i/bit_count
add wave -noupdate /tb_encode/i_top_wrapper/top_system_i/am_top_i/best_bit_count
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {136970196 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 160
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {16520250 ps} {17025251 ps}
